{
 "title": "Filebeat",
 "description": "Dashboard for Filebeat from Prometheus.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Ticks",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(filebeat_cpu_ticks_total[$interval])",
       "legendFormat": "{instance={{instance}}, mode={{mode}}}"
      }
     ]
    },
    {
     "title": "CPU Time Milliseconds",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(filebeat_cpu_time_seconds_total[$interval])*1000",
       "legendFormat": "{instance={{instance}}, mode={{mode}}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Filebeat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(filebeat_filebeat_events[$interval])",
       "legendFormat": "{instance={{instance}}, event={{event}}}"
      }
     ]
    },
    {
     "title": "Harvester",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(filebeat_filebeat_harvester[$interval])",
       "legendFormat": "{instance={{instance}}, harvester={{harvester}}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Libbeat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Libbeat Config",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(filebeat_libbeat_config[$interval])",
       "legendFormat": "{instance={{instance}}, module={{module}}}"
      }
     ]
    },
    {
     "title": "Libbeat Output",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(filebeat_libbeat_output_total[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Libbeat Output Events",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(filebeat_libbeat_output_events[$interval])",
       "legendFormat": "{instance={{instance}}, type={{type}}}"
      }
     ]
    },
    {
     "title": "Libbeat Output Read Bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(filebeat_libbeat_output_read_bytes_total[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Libbeat Output Read Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(filebeat_libbeat_output_read_errors_total[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Libbeat Output Write Bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(filebeat_libbeat_output_write_bytes_total[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Libbeat Output Write Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(filebeat_libbeat_output_write_errors_total[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Libbeat Pipeline Clients",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(filebeat_libbeat_pipeline_clients[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Libbeat Pipeline Queue",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(filebeat_libbeat_pipeline_queue[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Libbeat Pipeline Events",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "filebeat_libbeat_pipeline_events",
       "legendFormat": "{instance={{instance}}, type={{type}}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memstats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memstats GC Next",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(filebeat_memstats_gc_next_total[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memstats Memory Alloc",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(filebeat_memstats_memory_alloc[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memstats Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(filebeat_memstats_memory[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memstats RSS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(filebeat_memstats_rss[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Registrar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Registrar Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(filebeat_registrar_states[$interval])",
     "legendFormat": "{instance={{instance}}, state={{state}}}"
    }
   ]
  },
  {
   "title": "Registrar Writes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(filebeat_registrar_writes[$interval])",
     "legendFormat": "{instance={{instance}}, writes={{writes}}}"
    }
   ]
  },
  {
   "title": "Progress Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "filebeat_registrar_progress_size",
     "legendFormat": "{instance={{instance}}, size={{size}}}"
    }
   ]
  },
  {
   "title": "Progress Offset",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "filebeat_registrar_progress_offset",
     "legendFormat": "{instance={{instance}}, offset={{offset}}}"
    }
   ]
  },
  {
   "title": "Progress Backlog",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "filebeat_registrar_progress_backlog",
     "legendFormat": "{instance={{instance}}, backlog={{backlog}}}"
    }
   ]
  }
 ]
}